// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzgfrpdqvxxbruvfyeih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6Z2ZycGRxdnh4YnJ1dmZ5ZWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTI4MTYsImV4cCI6MjA2OTcyODgxNn0.SMcM_rnuTCSB9a98ORYaPSOMMcQMw7LLJOskyXP9ICg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});